// Generated by Haxe 4.0.0-rc.2+77068e1
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	var x = 0;
	var b = x++ + x++;
	console.log("src/Main.hx:7:",x);
};
Main.main();
})();
